name: Sync labels

on:
    push:
        branches: ["master"]

jobs:
    build:
        environment:
            name: production
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.14.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              env:
                  GITHUB_PAT: ${{ secrets.CUSTOM_PAT }}
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm run sync
